# Generated by Django 4.1.5 on 2023-01-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(choices=[('book', '책'), ('charger', '충전기'), ('calculator', '계산기'), ('student product', '학생용품'), ('etx', '그 외')], default='etx', max_length=40)),
                ('body', models.TextField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
